name: Auto-assign issue and add to project
on:
  issues:
    types: [opened]
jobs:
  run:
    name: Auto-assign issue and add to project
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: simplyNoOne
          numOfAssignee: 1
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: https://github.com/orgs/wall-street-stocks/projects/1
